#%RAML 1.0
title: MTIS Api Rest - Práctica 2
mediaType: application/json
baseUri: http://localhost:3000

/generarPresupuesto:
    post:
      description: Create a new Presupuesto and return its id
      queryParameters: 
        fechaPresupuesto:
          type: date
          description: Date YYYY-MM-DD
          example: "2018/03/25"
        idCliente:
          type: integer
        referenciaProducto:
          type: string
        cantidadProducto:
          type: integer        
        RestKey:
          type: string
      responses:
        200:
          description: The request was OK, check body response
          body: 
            application/json:
              example:
                {"data": {"codigoPostal":string.format("YYYY-MM-DD"),
                  "poblacion":string,
                  "provincia":string,
                  "existe":boolean
                }}
        400:
          description: Some queryParameters are missing
        403:
          description: You have not permission to use this action
        404:
          description: CP not found
        500:
          description: Server Internal Error