#%RAML 1.0
title: Contrato 3 - MTIS PR2
mediaType: application/json
baseUri: http://localhost:3000

/generarPresupuesto:
    post:
      description: Create a new Presupuesto and return its id
      queryParameters: 
        fechaPresupuesto:
          type: datetime
          description: Date YYYY-MM-DD
        idCliente:
          type: integer
        referenciaProducto:
          type: string
        cantidadProducto:
          type: integer        
        RestKey:
          type: string
      responses:
        200:
          description: The request was OK, check body response
          body: 
            application/json:
              example:
                {"data": {"idPresupuesto": integer, "presupuestoGenerado": boolean}}
        400:
          description: Some queryParameters are missing
        403:
          description: You have not permission to use this action
        500:
          description: Server Internal Error